directories:
  output: dist-electron
  buildResources: build
appId: com.yourcompany.ido-data-extractor
productName: IDO Data Extractor
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
win:
  target: nsis
  icon: public/favicon.ico
mac:
  target: dmg
  icon: public/favicon.ico
linux:
  target: AppImage
  icon: public/favicon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 28.3.3
